### ISSUE TITLE
Masalah dengan shopping cart

### ISSUE THREAD

**Issue by Capetian** [2018-PemrogramanWeb-D/tugas7-fp-proposal-xstore#1]
-Akun beda, shopping cart sama
- Jika shopping cart kosong akan muncul: Warning : Invalid argument supplied for foreach() in C:\xampp\htdocs\tugas7-fp-proposal-xstore\cart.php on line 158
- tombol merah di shopping cart(untuk menghapus barang?) tidak berfungsi
- checkout tombol checkout di shopping cart tidak berfungsi

**Comment by n0tlu5** [comment]
tombol tambah dan kurang tidak berfungsi

**Comment by hendraramadani** [comment]
![ketika register dengan akun baru dan login yang ditampilkan akun yang terdahulu](https://user-images.githubusercontent.com/36802769/50163094-4e550480-0312-11e9-9974-d73626d2443f.jpg)
![ketika register dengan akun baru dan login yang ditampilkan akun yang terdahulu2](https://user-images.githubusercontent.com/36802769/50163096-4e550480-0312-11e9-954f-c4aaab06d158.jpg)
![ketika register dengan akun baru dan login yang ditampilkan akun yang terdahulu3](https://user-images.githubusercontent.com/36802769/50163097-4eed9b00-0312-11e9-8688-db754c22dd7f.jpg)
![ketika login lalu pilih chart menampilkan chart akun yang terdahulu](https://user-images.githubusercontent.com/36802769/50163052-367d8080-0312-11e9-94df-4b80f4a9d79d.jpg)

**Comment by siannas** [comment]
Terima kasih atas bantuannya
