### ISSUE TITLE
Masalah akun

### ISSUE THREAD

**Issue by 051mym** [2018-PemrogramanWeb-D/tugas7-fp-proposal-xstore#3]
Nama pengguna yang ditampilkan pada profil tidak sesuai.
![screenshot 77](https://user-images.githubusercontent.com/42793951/50149955-299b6580-02ef-11e9-9e63-9ec85e50f1ba.png)

Nama yang ditampilkan selalu nama pertama pada database detail_orang.
![xstore2](https://user-images.githubusercontent.com/42793951/50150010-5485b980-02ef-11e9-839f-2618c65ea1e7.JPG)

**Comment by siannas** [comment]
Terima Kasih atas bantuannya
