### ISSUE TITLE
Undefined offset

### ISSUE THREAD

**Issue by 051mym** [2018-PemrogramanWeb-D/tugas7-fp-proposal-xstore#4]
Kadang saat pilih barang muncul **Notice :** blablablablah

![xstore](https://user-images.githubusercontent.com/42793951/50125364-1363ba00-029b-11e9-9f22-c99847b50d26.JPG)

**Comment by Neorocket64** [comment]
Masalah besar saat memilih barang
![capture](https://user-images.githubusercontent.com/17949796/50191712-9a7b6580-0361-11e9-8389-85ec34c3b79a.PNG)
