### ISSUE TITLE
Register issue

### ISSUE THREAD

**Issue by Armunz** [2018-PemrogramanWeb-D/tugas7-fp-proposal-xstore#5]
ketika sukses register, tidak diarahkan ke halaman login.
![ketika register dengan akun baru dan login yang ditampilkan akun yang terdahulu](https://user-images.githubusercontent.com/36951196/50163372-e18e3a00-0312-11e9-9256-a06cad1e702b.jpg)
![setelah selesai register tidak diarahkan ke halaman login](https://user-images.githubusercontent.com/36951196/50163373-e18e3a00-0312-11e9-973a-3b8b1b8dc858.jpg)

**Comment by Armunz** [comment]
Register nama dengan angka
![register nama dengan angka masih bisa](https://user-images.githubusercontent.com/36951196/50163488-21552180-0313-11e9-91aa-834680177d48.jpg)

**Comment by siannas** [comment]
Terima Kasih sudah membantu kami

**Comment by ridho13** [comment]
utk memfix bug tlg sertakan referensi ke commit-an dmn terdapat fix bugnya.
contoh bs dilihat di https://github.com/2018-PemrogramanWeb-D/tugas7-fp-ngr/issues/3

mhdfadlyhasan closed this in 9aef5ad 5 hours ago
